### ISSUE TITLE
Is there a way to chage the percentage?

### ISSUE THREAD

**Issue by ebaystudio** [OffsetMods538/CobbleOre-Generator#1]
Sorry, not really an issue but I didn't see a way to contact you on Modrinth. Is there any way to change the percentage of ore to cobble? I went over all the code and didn't see anything that would hint at a percentage. 
I'm using your 1.19 version. 

Would be great if it had a config or you could point me in the right direction to edit it myself. Thanks

**Comment by OffsetMonkey538** [comment]
Hmm, I remember that I added a config option at one point, but I guess I didn't? I might do that later today if I remember lol. Also I have a [discord server](https://discord.offsetmonkey538.top) which

**Comment by ebaystudio** [comment]
Would be awesome if you could. I'm on 1.19 and have it working with Create but a single stack of any ore takes like an hour and its tearing though pickaxes like crazy.  I'm not good with Discord but if you need me to join to get a config Ill figure it out. Thanks again for the mod.

**Comment by JackYevhen** [comment]
Only one question: (In later versions config already exists) The numbers there: I. must they be integers (or also can be non-full numbers (floats)) II. Are these numbers presents or weights?

**Comment by OffsetMonkey538** [comment]
The values are stored as integers and they're weights.
For examle if you set ores to 37 and cobblestone to 86, then 37 times out of 37+86=123 it would spawn ores and 86 times of 123 it would spawn cobblestone.

**Comment by JackYevhen** [comment]
Thanks (I do know how weights work, after all Iv messed a lot with loot tables in my data packs). One more suggestion: make config more loot table-like.
(I mean make it so there can be conditions, like in this loot table) [loot table]:
What it does:
1. If diamond block is bellow:
    * if deepslate is above: deepslate diamond ore
    * if stone is above: normal diamond ore
    * if not any of those: diorite
2. if lava is bellow:
    * 1 / 10 - nether gold ore
    * 9 / 10 - netherrack 
```
{
  "type": "minecraft:command",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "weight": 100,
          "name": "minecraft:diamond_ore",
          "conditions": [
            {
              "condition": "minecraft:location_check",
              "offsetY": 1,
              "predicate": {
                "block": {
                  "blocks": [
                    "minecraft:stone"
                  ]
                }
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "weight": 100,
          "name": "minecraft:deepslate_diamond_ore",
          "conditions": [
            {
              "condition": "minecraft:location_check",
              "offsetY": 1,
              "predicate": {
                "block": {
                  "blocks": [
                    "minecraft:deepslate"
                  ]
                }
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "weight": 1,
          "name": "minecraft:diorite"
        }
      ],
      "conditions": [
        {
          "condition": "minecraft:location_check",
          "offsetY": -1,
          "predicate": {
            "block": {
              "blocks": [
                "minecraft:diamond_block"
              ]
            }
          }
        }
      ]
    },
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "weight": 9,
          "name": "minecraft:netherrack"
        },
        {
          "type": "minecraft:item",
          "weight": 1,
          "name": "minecraft:nether_gold_ore"
        }
      ],
      "conditions": [
        {
          "condition": "minecraft:location_check",
          "offsetY": -1,
          "predicate": {
            "fluid": {
              "fluid": "minecraft:lava"
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by OffsetMonkey538** [comment]
This seems kind of interesting. Could we move this into a separate issue?

**Comment by OffsetMonkey538** [comment]
Also this issue should be closed
